site_name: Iter8
site_url: https://iter8.tools/latest
site_author: Srinivasan Parthasarathy
site_description: >-
  Iter8 is the Kubernetes release optimizer built for DevOps, MLOps, SRE and data science teams. Iter8 makes it easy to ensure that Kubernetes apps and ML models perform well and maximize business value.
# Repository
repo_name: iter8-tools/iter8
repo_url: https://github.com/iter8-tools/iter8
edit_uri: ""

# Configuration
theme:
  name: material
  custom_dir: overrides

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
  - navigation.instant
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.indexes
  palette:
  - scheme: primary
    primary: black
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  logo: images/logo.svg

# Plugins
plugins:
- search
- tags
- minify:
    minify_html: true
- mike

# Customization
extra:
  # Google Analytics
  analytics:
    provider: google
    property: UA-152813895-1

  title: Kubernetes Release Optimizer
  version:
    provider: mike
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/iter8-tools/iter8
  - icon: fontawesome/brands/slack
    link: https://join.slack.com/t/iter8-tools/shared_invite/zt-awl2se8i-L0pZCpuHntpPejxzLicbmw

  generator: false

copyright: Iter8 is open-source and available under the Apache 2 License.

# Extensions
markdown_extensions:
- admonition
- abbr
- attr_list
- def_list
- footnotes
- md_in_html
- meta
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink:
    repo_url_shorthand: true
    user: iter8-tools
    repo: iter8
- pymdownx.smartsymbols
- pymdownx.snippets: 
    base_path:
    - "./"
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true 
- pymdownx.tasklist:
    custom_checkbox: true
- tables
- toc:
    permalink: true

# Page tree
nav:
- Home: index.md
- Getting Started:
  - Your first experiment: getting-started/your-first-experiment.md
  - Concepts: getting-started/concepts.md
  - Install Iter8: getting-started/install.md
- Tutorials:
  - A/B testing: 
    - Quick start: tutorials/abn/quickstart.md
  # - Performance testing:
  #   - HTTP: tutorials/load-test-http.md
  #   - gRPC: tutorials/load-test-grpc.md
  - Traffic engineering: 
    - Mirroring: tutorials/traffic-engineering/mirroring.md
  # - Custom metrics: 
  #   - Prometheus: tutorials/custom-metrics/prometheus.md
# - Integrations:
#   - Kserve:
#     - Performance testing:
#       - HTTP: integrations/kserve/http.md
#       - gRPC: integrations/kserve/grpc.md
#     - Canary testing: integrations/kserve/canary-testing.md
#     - Custom metrics: integrations/kserve/custom-metrics.md
#     - Other (Iter8 v0.7): integrations/kserve/kserve.md
#   - Knative: integrations/knative.md
#   - Istio: integrations/istio.md
#   - Seldon: integrations/seldon.md
#   - Litmus: integrations/litmus/chaos.md
#   - Linkerd: integrations/linkerd.md
- User guide:
  - Topics:
    - Subject: user-guide/topics/subject.md
    - Experiment: user-guide/topics/experiment.md
    - Weights: user-guide/topics/weights.md
    # - Experiment parameters: user-guide/topics/parameters.md
    # - Metrics: user-guide/topics/metrics.md
    - A/B/n testing:
      - Iter8 service: user-guide/topics/abn/service.md
      - Iter8 SDK: user-guide/topics/abn/sdk.md
    # - Namespace and group: user-guide/topics/group.md
  - Tasks:
    - abnmetrics: user-guide/tasks/abnmetrics.md
    - assess: user-guide/tasks/assess.md
    - custommetrics: user-guide/tasks/custommetrics.md
    - github: user-guide/tasks/github.md
    - grpc: user-guide/tasks/grpc.md
    - http: user-guide/tasks/http.md
    - slack: user-guide/tasks/slack.md
    - ready: user-guide/tasks/ready.md
# - Glossary: glossary.md
# - Contributing: contributing.md
# - Community: 
#   - Community: community/community.md
#   - News: community/news.md
